from PyQt5 import QtWidgets, QtCore, QtGui


class CalendarItemWidget(QtWidgets.QWidget):
    def __init__(self, name, date, end, start, *args, **kwargs):
        QtWidgets.QWidget.__init__(self, *args, **kwargs)
        self.setGeometry(QtCore.QRect(0, 0, 274, 59))
        self.resize(274, 59)
        self.nameLabel = QtWidgets.QLabel(self)
        self.nameLabel.setGeometry(QtCore.QRect(0, 0, 274, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color: #ffffffff")
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLabel.setText(name)
        self.dateLabel = QtWidgets.QLabel(self)
        self.dateLabel.setGeometry(QtCore.QRect(0, 30, 73, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.dateLabel.setFont(font)
        self.dateLabel.setStyleSheet("color: #ffffffff")
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.dateLabel.setText(date)
        self.startLabel = QtWidgets.QLabel(self)
        self.startLabel.setGeometry(QtCore.QRect(121, 30, 53, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.startLabel.setFont(font)
        self.startLabel.setStyleSheet("color: #ffffffff")
        self.startLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startLabel.setObjectName("startLabel")
        self.startLabel.setText(start)
        self.endLabel = QtWidgets.QLabel(self)
        self.endLabel.setGeometry(QtCore.QRect(213, 30, 53, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        self.endLabel.setFont(font)
        self.endLabel.setStyleSheet("color: #ffffffff")
        self.endLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.endLabel.setObjectName("endLabel")
        self.endLabel.setText(end)
        self.toLabel = QtWidgets.QLabel(self)
        self.toLabel.setGeometry(QtCore.QRect(175, 32, 38, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(12)
        self.toLabel.setFont(font)
        self.toLabel.setStyleSheet("color: #ffffffff")
        self.toLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toLabel.setObjectName("toLabel")
        self.toLabel.setText("To")
        self.fromLabel = QtWidgets.QLabel(self)
        self.fromLabel.setGeometry(QtCore.QRect(70, 32, 44, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(12)
        self.fromLabel.setFont(font)
        self.fromLabel.setStyleSheet("color: #ffffffff")
        self.fromLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fromLabel.setObjectName("fromLabel")
        self.fromLabel.setText("From")