import requests
from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtGui import QPixmap


class WxForecastItemWidget(QtWidgets.QWidget):
    def __init__(self, day, image, high, low, *args, **kwargs):
        QtWidgets.QWidget.__init__(self, *args, **kwargs)
        self.setGeometry(QtCore.QRect(0, 0, 393, 50))
        self.resize(393, 50)
        self.dayLabel = QtWidgets.QLabel(self)
        self.dayLabel.setGeometry(QtCore.QRect(0, 0, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.dayLabel.setFont(font)
        self.dayLabel.setStyleSheet("color: #ffffffff")
        self.dayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dayLabel.setObjectName("dayLabel")
        self.dayLabel.setText(day)
        self.skyImage = QtWidgets.QLabel(self)
        self.skyImage.setGeometry(QtCore.QRect(130, 0, 80, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        self.skyImage.setFont(font)
        self.skyImage.setStyleSheet("color: #ffffffff")
        self.skyImage.setText("")
        self.skyImage.setAlignment(QtCore.Qt.AlignCenter)
        self.skyImage.setObjectName("skyImage")
        self.skyImage.setPixmap(image)
        self.highLabel = QtWidgets.QLabel(self)
        self.highLabel.setGeometry(QtCore.QRect(232, 0, 74, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.highLabel.setFont(font)
        self.highLabel.setStyleSheet("color: #ffffffff")
        self.highLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.highLabel.setObjectName("highLabel")
        self.highLabel.setText(high)
        self.lowLabel = QtWidgets.QLabel(self)
        self.lowLabel.setGeometry(QtCore.QRect(319, 0, 74, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        self.lowLabel.setFont(font)
        self.lowLabel.setStyleSheet("color: #ffffffff")
        self.lowLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lowLabel.setObjectName("lowLabel")
        self.lowLabel.setText(low)